FROM golang:1.9

RUN apt-get update
RUN apt-get install curl --yes


RUN curl https://glide.sh/get | sh

RUN mkdir -p $GOPATH/src/github.com/andrepinto/helmsman

VOLUME  /go/src/github.com/andrepinto/helmsman/bin

COPY . $GOPATH/src/github.com/andrepinto/helmsman

WORKDIR $GOPATH/src/github.com/andrepinto/helmsman

RUN glide install
